// Code generated by protoc-gen-go.
// source: data.proto
// DO NOT EDIT!

package mtrpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// DataLatencySummary is a summary of data latency metrics for each site.
// mean should not be 0.  fifty and ninety may be unknown (0).
// If upper == lower == 0 then no threshold has been set on the metric.
type DataLatencySummary struct {
	// The siteID for the metric e.g., TAUP
	SiteID string `protobuf:"bytes,1,opt,name=site_iD" json:"site_iD,omitempty"`
	// The typeID for the metric e.g., latency.strong
	TypeID string `protobuf:"bytes,2,opt,name=type_iD" json:"type_iD,omitempty"`
	// Unix time in seconds for the metric value (don't need nanos).
	Seconds int64 `protobuf:"varint,3,opt,name=seconds" json:"seconds,omitempty"`
	// The mean latency
	Mean int32 `protobuf:"varint,4,opt,name=mean" json:"mean,omitempty"`
	// The fiftieth percentile value.  Might be unknown (0)
	Fifty int32 `protobuf:"varint,5,opt,name=fifty" json:"fifty,omitempty"`
	// The ninetieth percentile value.  Might be unknown (0)
	Ninety int32 `protobuf:"varint,6,opt,name=ninety" json:"ninety,omitempty"`
	// The upper threshold for the metric to be good.
	Upper int32 `protobuf:"varint,7,opt,name=upper" json:"upper,omitempty"`
	// The lower threshold for the metric to be good.
	Lower int32 `protobuf:"varint,8,opt,name=lower" json:"lower,omitempty"`
}

func (m *DataLatencySummary) Reset()                    { *m = DataLatencySummary{} }
func (m *DataLatencySummary) String() string            { return proto.CompactTextString(m) }
func (*DataLatencySummary) ProtoMessage()               {}
func (*DataLatencySummary) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type DataLatencySummaryResult struct {
	Result []*DataLatencySummary `protobuf:"bytes,1,rep,name=result" json:"result,omitempty"`
}

func (m *DataLatencySummaryResult) Reset()                    { *m = DataLatencySummaryResult{} }
func (m *DataLatencySummaryResult) String() string            { return proto.CompactTextString(m) }
func (*DataLatencySummaryResult) ProtoMessage()               {}
func (*DataLatencySummaryResult) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *DataLatencySummaryResult) GetResult() []*DataLatencySummary {
	if m != nil {
		return m.Result
	}
	return nil
}

type DataSite struct {
	// The siteID for the metric e.g., TAUP
	SiteID string `protobuf:"bytes,1,opt,name=site_iD" json:"site_iD,omitempty"`
	// The site latitude - not usually accurate enough for meta data
	Latitude float64 `protobuf:"fixed64,2,opt,name=latitude" json:"latitude,omitempty"`
	// The site longitude - not usually accurate enough for meta data
	Longitude float64 `protobuf:"fixed64,3,opt,name=longitude" json:"longitude,omitempty"`
}

func (m *DataSite) Reset()                    { *m = DataSite{} }
func (m *DataSite) String() string            { return proto.CompactTextString(m) }
func (*DataSite) ProtoMessage()               {}
func (*DataSite) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

type DataSiteResult struct {
	Result []*DataSite `protobuf:"bytes,1,rep,name=result" json:"result,omitempty"`
}

func (m *DataSiteResult) Reset()                    { *m = DataSiteResult{} }
func (m *DataSiteResult) String() string            { return proto.CompactTextString(m) }
func (*DataSiteResult) ProtoMessage()               {}
func (*DataSiteResult) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *DataSiteResult) GetResult() []*DataSite {
	if m != nil {
		return m.Result
	}
	return nil
}

type DataLatencyTag struct {
	// The siteID for the latency e.g., TAUP
	SiteID string `protobuf:"bytes,1,opt,name=site_iD" json:"site_iD,omitempty"`
	// The typeID for the latency e.g., latency.gnss.1hz
	TypeID string `protobuf:"bytes,2,opt,name=type_iD" json:"type_iD,omitempty"`
	// The tag for the latency e.g., TAUP
	Tag string `protobuf:"bytes,3,opt,name=tag" json:"tag,omitempty"`
}

func (m *DataLatencyTag) Reset()                    { *m = DataLatencyTag{} }
func (m *DataLatencyTag) String() string            { return proto.CompactTextString(m) }
func (*DataLatencyTag) ProtoMessage()               {}
func (*DataLatencyTag) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

type DataLatencyTagResult struct {
	Result []*DataLatencyTag `protobuf:"bytes,1,rep,name=result" json:"result,omitempty"`
}

func (m *DataLatencyTagResult) Reset()                    { *m = DataLatencyTagResult{} }
func (m *DataLatencyTagResult) String() string            { return proto.CompactTextString(m) }
func (*DataLatencyTagResult) ProtoMessage()               {}
func (*DataLatencyTagResult) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *DataLatencyTagResult) GetResult() []*DataLatencyTag {
	if m != nil {
		return m.Result
	}
	return nil
}

type DataLatencyThreshold struct {
	// The siteID for the latency e.g., TAUP
	SiteID string `protobuf:"bytes,1,opt,name=site_iD" json:"site_iD,omitempty"`
	// The typeID for the latency e.g., latency.gnss.1hz
	TypeID string `protobuf:"bytes,2,opt,name=type_iD" json:"type_iD,omitempty"`
	// The lower threshold for the latency to be good.
	Lower int32 `protobuf:"varint,3,opt,name=lower" json:"lower,omitempty"`
	// The upper threshold for the latency to be good.
	Upper int32 `protobuf:"varint,4,opt,name=upper" json:"upper,omitempty"`
}

func (m *DataLatencyThreshold) Reset()                    { *m = DataLatencyThreshold{} }
func (m *DataLatencyThreshold) String() string            { return proto.CompactTextString(m) }
func (*DataLatencyThreshold) ProtoMessage()               {}
func (*DataLatencyThreshold) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

type DataLatencyThresholdResult struct {
	Result []*DataLatencyThreshold `protobuf:"bytes,1,rep,name=result" json:"result,omitempty"`
}

func (m *DataLatencyThresholdResult) Reset()                    { *m = DataLatencyThresholdResult{} }
func (m *DataLatencyThresholdResult) String() string            { return proto.CompactTextString(m) }
func (*DataLatencyThresholdResult) ProtoMessage()               {}
func (*DataLatencyThresholdResult) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *DataLatencyThresholdResult) GetResult() []*DataLatencyThreshold {
	if m != nil {
		return m.Result
	}
	return nil
}

type DataType struct {
	// The TypeID in the table data.type
	TypeID string `protobuf:"bytes,1,opt,name=type_iD" json:"type_iD,omitempty"`
}

func (m *DataType) Reset()                    { *m = DataType{} }
func (m *DataType) String() string            { return proto.CompactTextString(m) }
func (*DataType) ProtoMessage()               {}
func (*DataType) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

type DataTypeResult struct {
	Result []*DataType `protobuf:"bytes,1,rep,name=result" json:"result,omitempty"`
}

func (m *DataTypeResult) Reset()                    { *m = DataTypeResult{} }
func (m *DataTypeResult) String() string            { return proto.CompactTextString(m) }
func (*DataTypeResult) ProtoMessage()               {}
func (*DataTypeResult) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *DataTypeResult) GetResult() []*DataType {
	if m != nil {
		return m.Result
	}
	return nil
}

// DataLatency represents a series of metric for a site+type.
type DataLatency struct {
	// Unix time in seconds for the metric value (don't need nanos).
	Seconds int64 `protobuf:"varint,1,opt,name=seconds" json:"seconds,omitempty"`
	// The mean latency
	Mean float32 `protobuf:"fixed32,2,opt,name=mean" json:"mean,omitempty"`
	// The fiftieth percentile value.  Might be unknown (0)
	Fifty int32 `protobuf:"varint,3,opt,name=fifty" json:"fifty,omitempty"`
	// The ninetieth percentile value.  Might be unknown (0)
	Ninety int32 `protobuf:"varint,4,opt,name=ninety" json:"ninety,omitempty"`
}

func (m *DataLatency) Reset()                    { *m = DataLatency{} }
func (m *DataLatency) String() string            { return proto.CompactTextString(m) }
func (*DataLatency) ProtoMessage()               {}
func (*DataLatency) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

type DataLatencyResult struct {
	// The siteID for the metric e.g., TAUP
	SiteID string `protobuf:"bytes,1,opt,name=site_iD" json:"site_iD,omitempty"`
	// The typeID for the metric e.g., latency.strong
	TypeID string `protobuf:"bytes,2,opt,name=type_iD" json:"type_iD,omitempty"`
	// The upper threshold for the metric to be good.
	Upper int32 `protobuf:"varint,3,opt,name=upper" json:"upper,omitempty"`
	// The lower threshold for the metric to be good.
	Lower  int32          `protobuf:"varint,4,opt,name=lower" json:"lower,omitempty"`
	Result []*DataLatency `protobuf:"bytes,5,rep,name=result" json:"result,omitempty"`
}

func (m *DataLatencyResult) Reset()                    { *m = DataLatencyResult{} }
func (m *DataLatencyResult) String() string            { return proto.CompactTextString(m) }
func (*DataLatencyResult) ProtoMessage()               {}
func (*DataLatencyResult) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

func (m *DataLatencyResult) GetResult() []*DataLatency {
	if m != nil {
		return m.Result
	}
	return nil
}

// DataCompletenessSummary is metrics to let us determine if all the data had arrived.
// The "completenss" value is derived from:
//    {count in a period of time (no less than 5 minutes)} / { expected count im a period of time }
// For example, a site(type) expects 300 counts in 5 minutes (1hz),
//    but got 270 counts for the latest 5 minutes then its latest completeness will be 0.9 .
type DataCompletenessSummary struct {
	// The siteID for the completeness e.g., TAUP
	SiteID string `protobuf:"bytes,1,opt,name=site_iD" json:"site_iD,omitempty"`
	// The typeID for the completeness e.g., gnss.1hz
	TypeID string `protobuf:"bytes,2,opt,name=type_iD" json:"type_iD,omitempty"`
	// Unix time in seconds for the metric value (don't need nanos).
	Seconds int64 `protobuf:"varint,3,opt,name=seconds" json:"seconds,omitempty"`
	// The completeness for a given period of time
	Completeness float32 `protobuf:"fixed32,4,opt,name=completeness" json:"completeness,omitempty"`
}

func (m *DataCompletenessSummary) Reset()                    { *m = DataCompletenessSummary{} }
func (m *DataCompletenessSummary) String() string            { return proto.CompactTextString(m) }
func (*DataCompletenessSummary) ProtoMessage()               {}
func (*DataCompletenessSummary) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

type DataCompletenessSummaryResult struct {
	Result []*DataCompletenessSummary `protobuf:"bytes,1,rep,name=result" json:"result,omitempty"`
}

func (m *DataCompletenessSummaryResult) Reset()                    { *m = DataCompletenessSummaryResult{} }
func (m *DataCompletenessSummaryResult) String() string            { return proto.CompactTextString(m) }
func (*DataCompletenessSummaryResult) ProtoMessage()               {}
func (*DataCompletenessSummaryResult) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

func (m *DataCompletenessSummaryResult) GetResult() []*DataCompletenessSummary {
	if m != nil {
		return m.Result
	}
	return nil
}

type DataCompletenessTag struct {
	// The siteID for the latency e.g., TAUP
	SiteID string `protobuf:"bytes,1,opt,name=site_iD" json:"site_iD,omitempty"`
	// The typeID for the latency e.g., gnss.1hz
	TypeID string `protobuf:"bytes,2,opt,name=type_iD" json:"type_iD,omitempty"`
	// The tag for the latency e.g., TAUP
	Tag string `protobuf:"bytes,3,opt,name=tag" json:"tag,omitempty"`
}

func (m *DataCompletenessTag) Reset()                    { *m = DataCompletenessTag{} }
func (m *DataCompletenessTag) String() string            { return proto.CompactTextString(m) }
func (*DataCompletenessTag) ProtoMessage()               {}
func (*DataCompletenessTag) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{14} }

type DataCompletenessTagResult struct {
	Result []*DataCompletenessTag `protobuf:"bytes,1,rep,name=result" json:"result,omitempty"`
}

func (m *DataCompletenessTagResult) Reset()                    { *m = DataCompletenessTagResult{} }
func (m *DataCompletenessTagResult) String() string            { return proto.CompactTextString(m) }
func (*DataCompletenessTagResult) ProtoMessage()               {}
func (*DataCompletenessTagResult) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{15} }

func (m *DataCompletenessTagResult) GetResult() []*DataCompletenessTag {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*DataLatencySummary)(nil), "mtrpb.DataLatencySummary")
	proto.RegisterType((*DataLatencySummaryResult)(nil), "mtrpb.DataLatencySummaryResult")
	proto.RegisterType((*DataSite)(nil), "mtrpb.DataSite")
	proto.RegisterType((*DataSiteResult)(nil), "mtrpb.DataSiteResult")
	proto.RegisterType((*DataLatencyTag)(nil), "mtrpb.DataLatencyTag")
	proto.RegisterType((*DataLatencyTagResult)(nil), "mtrpb.DataLatencyTagResult")
	proto.RegisterType((*DataLatencyThreshold)(nil), "mtrpb.DataLatencyThreshold")
	proto.RegisterType((*DataLatencyThresholdResult)(nil), "mtrpb.DataLatencyThresholdResult")
	proto.RegisterType((*DataType)(nil), "mtrpb.DataType")
	proto.RegisterType((*DataTypeResult)(nil), "mtrpb.DataTypeResult")
	proto.RegisterType((*DataLatency)(nil), "mtrpb.DataLatency")
	proto.RegisterType((*DataLatencyResult)(nil), "mtrpb.DataLatencyResult")
	proto.RegisterType((*DataCompletenessSummary)(nil), "mtrpb.DataCompletenessSummary")
	proto.RegisterType((*DataCompletenessSummaryResult)(nil), "mtrpb.DataCompletenessSummaryResult")
	proto.RegisterType((*DataCompletenessTag)(nil), "mtrpb.DataCompletenessTag")
	proto.RegisterType((*DataCompletenessTagResult)(nil), "mtrpb.DataCompletenessTagResult")
}

var fileDescriptor1 = []byte{
	// 458 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x54, 0x5d, 0xab, 0xd3, 0x40,
	0x10, 0x25, 0x4d, 0x93, 0xb6, 0xd3, 0xda, 0xda, 0xb5, 0x62, 0xda, 0xe2, 0x07, 0x0b, 0x42, 0x55,
	0x08, 0xa8, 0xcf, 0xa2, 0x68, 0x45, 0x44, 0x41, 0xb0, 0xc5, 0x07, 0x5f, 0x64, 0xdb, 0x6c, 0xdb,
	0x40, 0xbe, 0x48, 0x36, 0x94, 0xfc, 0x0d, 0x7f, 0xf1, 0xdd, 0xdd, 0x24, 0xbd, 0xf9, 0x2a, 0x84,
	0x7b, 0xdf, 0x32, 0x67, 0x77, 0xe6, 0x9c, 0x33, 0x33, 0x59, 0x00, 0x8b, 0x30, 0x62, 0x06, 0xa1,
	0xcf, 0x7c, 0xa4, 0xb9, 0x2c, 0x0c, 0x76, 0xf8, 0xbf, 0x02, 0x68, 0xcd, 0xd1, 0x9f, 0x84, 0x51,
	0x6f, 0x9f, 0x6c, 0x62, 0xd7, 0x25, 0x61, 0x82, 0x26, 0xd0, 0x8b, 0x6c, 0x46, 0xff, 0xd9, 0x6b,
	0x43, 0x79, 0xa1, 0xac, 0x06, 0x02, 0x60, 0x49, 0x20, 0x81, 0x4e, 0x0e, 0x44, 0x74, 0xef, 0x7b,
	0x56, 0x64, 0xa8, 0x1c, 0x50, 0xd1, 0x08, 0xba, 0x2e, 0x25, 0x9e, 0xd1, 0xe5, 0x91, 0x86, 0x1e,
	0x80, 0x76, 0xb0, 0x0f, 0x2c, 0x31, 0x34, 0x19, 0x8e, 0x41, 0xf7, 0x6c, 0x8f, 0xf2, 0x58, 0xcf,
	0x8f, 0xe3, 0x20, 0xa0, 0xa1, 0xd1, 0xcb, 0x43, 0xc7, 0x3f, 0xf3, 0xb0, 0x2f, 0x42, 0xfc, 0x15,
	0x8c, 0xba, 0xa6, 0xdf, 0x34, 0x8a, 0x1d, 0x86, 0x5e, 0x81, 0x1e, 0xca, 0x2f, 0x2e, 0x4c, 0x5d,
	0x0d, 0xdf, 0xcd, 0x4d, 0x69, 0xc4, 0xac, 0x27, 0xe0, 0x4f, 0xd0, 0x17, 0xe8, 0x86, 0x1b, 0xa9,
	0x1b, 0x7a, 0x08, 0x7d, 0x87, 0x30, 0x9b, 0xc5, 0x16, 0x95, 0x8e, 0x14, 0x34, 0x85, 0x81, 0xe3,
	0x7b, 0xc7, 0x14, 0x12, 0x9e, 0x14, 0xfc, 0x16, 0xc6, 0x79, 0x85, 0x8c, 0xfe, 0x79, 0x85, 0x7e,
	0x52, 0xa0, 0x17, 0xd7, 0xf0, 0xc7, 0x34, 0x25, 0x93, 0xb2, 0x25, 0xc7, 0x16, 0xbd, 0x1c, 0x82,
	0xca, 0xc8, 0x51, 0x72, 0x0e, 0xf0, 0x07, 0x98, 0x95, 0x0b, 0x64, 0xcc, 0x2f, 0x2b, 0xcc, 0x8f,
	0xeb, 0xc6, 0xf9, 0x65, 0xfc, 0xa7, 0x9c, 0x7e, 0xe2, 0x39, 0x27, 0xdf, 0xb1, 0x5a, 0xa8, 0xb8,
	0x0c, 0x41, 0x2d, 0x8f, 0x48, 0x0e, 0x14, 0x7f, 0x87, 0x45, 0x53, 0xdd, 0x4c, 0xdc, 0x9b, 0x8a,
	0xb8, 0x65, 0x83, 0xb8, 0x3c, 0x05, 0x2f, 0xd3, 0xb9, 0x6c, 0x39, 0x7b, 0x51, 0x85, 0x94, 0x95,
	0xb7, 0x5c, 0x1c, 0xb6, 0x68, 0xb9, 0xb8, 0x86, 0x7f, 0xc0, 0xb0, 0xc0, 0x53, 0xdc, 0x4c, 0xa5,
	0xb4, 0x99, 0xc2, 0x66, 0xe7, 0x76, 0x33, 0xd5, 0xca, 0x66, 0xa6, 0x3e, 0xcf, 0x30, 0x2d, 0x14,
	0xcb, 0x24, 0xb4, 0x6a, 0x5e, 0xda, 0x2d, 0xb5, 0xbc, 0xd0, 0xe9, 0xdf, 0x80, 0x2f, 0x16, 0x34,
	0x69, 0x01, 0xd5, 0xdb, 0x83, 0x77, 0xf0, 0x44, 0x84, 0x5f, 0x7c, 0x37, 0x70, 0x28, 0x87, 0x68,
	0x14, 0xdd, 0xe3, 0x6f, 0x9c, 0xc1, 0x68, 0x5f, 0xa8, 0x24, 0x75, 0x74, 0xf0, 0x2f, 0x78, 0x7a,
	0x85, 0x23, 0x33, 0x6a, 0x56, 0x7a, 0xfd, 0xac, 0x20, 0xb4, 0x21, 0x0b, 0xaf, 0xe1, 0x51, 0xf5,
	0xe8, 0x0e, 0x2b, 0xff, 0x0d, 0xe6, 0x0d, 0x55, 0x32, 0x49, 0xaf, 0x2b, 0x92, 0x16, 0x57, 0x24,
	0xf1, 0x8c, 0xcf, 0xbd, 0xbf, 0xe9, 0xb3, 0xb6, 0xd3, 0xe5, 0x23, 0xf7, 0xfe, 0x26, 0x00, 0x00,
	0xff, 0xff, 0x35, 0xc2, 0x44, 0x66, 0xf2, 0x04, 0x00, 0x00,
}
