// Code generated by protoc-gen-go.
// source: field.proto
// DO NOT EDIT!

package mtrpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// FieldMetricSummary is the latest value received for a field metric and thresholds for the metric.
// If upper == lower == 0 then no threshold has been set on the metric.
type FieldMetricSummary struct {
	// The deviceID for the metric e.g., idu-birchfarm
	DeviceID string `protobuf:"bytes,1,opt,name=device_iD,json=deviceID" json:"device_iD,omitempty"`
	// The typeID for the metric e.g., conn
	TypeID string `protobuf:"bytes,2,opt,name=type_iD,json=typeID" json:"type_iD,omitempty"`
	// Unix time in seconds for the metric value (don't need nanos).
	Seconds int64 `protobuf:"varint,3,opt,name=seconds" json:"seconds,omitempty"`
	// The value
	Value int32 `protobuf:"varint,4,opt,name=value" json:"value,omitempty"`
	// The upper threshold for the metric to be good.
	Upper int32 `protobuf:"varint,5,opt,name=upper" json:"upper,omitempty"`
	// The lower threshold for the metric to be good.
	Lower int32 `protobuf:"varint,6,opt,name=lower" json:"lower,omitempty"`
	// the modelID for the device e.g., "Trimble NetR9"
	ModelID string `protobuf:"bytes,7,opt,name=model_iD,json=modelID" json:"model_iD,omitempty"`
}

func (m *FieldMetricSummary) Reset()                    { *m = FieldMetricSummary{} }
func (m *FieldMetricSummary) String() string            { return proto.CompactTextString(m) }
func (*FieldMetricSummary) ProtoMessage()               {}
func (*FieldMetricSummary) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type FieldMetricSummaryResult struct {
	Result []*FieldMetricSummary `protobuf:"bytes,1,rep,name=result" json:"result,omitempty"`
}

func (m *FieldMetricSummaryResult) Reset()                    { *m = FieldMetricSummaryResult{} }
func (m *FieldMetricSummaryResult) String() string            { return proto.CompactTextString(m) }
func (*FieldMetricSummaryResult) ProtoMessage()               {}
func (*FieldMetricSummaryResult) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *FieldMetricSummaryResult) GetResult() []*FieldMetricSummary {
	if m != nil {
		return m.Result
	}
	return nil
}

type FieldMetricTag struct {
	// The deviceID for the metric e.g., idu-birchfarm
	DeviceID string `protobuf:"bytes,1,opt,name=device_iD,json=deviceID" json:"device_iD,omitempty"`
	// The typeID for the metric e.g., conn
	TypeID string `protobuf:"bytes,2,opt,name=type_iD,json=typeID" json:"type_iD,omitempty"`
	// The tag for the metric e.g., TAUP
	Tag string `protobuf:"bytes,3,opt,name=tag" json:"tag,omitempty"`
}

func (m *FieldMetricTag) Reset()                    { *m = FieldMetricTag{} }
func (m *FieldMetricTag) String() string            { return proto.CompactTextString(m) }
func (*FieldMetricTag) ProtoMessage()               {}
func (*FieldMetricTag) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

type FieldMetricTagResult struct {
	Result []*FieldMetricTag `protobuf:"bytes,1,rep,name=result" json:"result,omitempty"`
}

func (m *FieldMetricTagResult) Reset()                    { *m = FieldMetricTagResult{} }
func (m *FieldMetricTagResult) String() string            { return proto.CompactTextString(m) }
func (*FieldMetricTagResult) ProtoMessage()               {}
func (*FieldMetricTagResult) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *FieldMetricTagResult) GetResult() []*FieldMetricTag {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*FieldMetricSummary)(nil), "mtrpb.FieldMetricSummary")
	proto.RegisterType((*FieldMetricSummaryResult)(nil), "mtrpb.FieldMetricSummaryResult")
	proto.RegisterType((*FieldMetricTag)(nil), "mtrpb.FieldMetricTag")
	proto.RegisterType((*FieldMetricTagResult)(nil), "mtrpb.FieldMetricTagResult")
}

var fileDescriptor1 = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x91, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xa9, 0xb5, 0xcd, 0xfa, 0x06, 0x22, 0x61, 0x62, 0x86, 0x17, 0xe9, 0x69, 0x17, 0x0b,
	0xea, 0x7f, 0x20, 0x55, 0xd8, 0x61, 0x97, 0xe8, 0x41, 0xbc, 0x48, 0xd7, 0xc6, 0x51, 0x48, 0x4d,
	0x48, 0xd3, 0xc9, 0xfe, 0x3c, 0xff, 0x33, 0x93, 0x97, 0x0a, 0xea, 0x3c, 0xed, 0xf6, 0xbe, 0x9f,
	0xef, 0x4b, 0xde, 0x2f, 0x98, 0xbe, 0xb5, 0x42, 0x36, 0x85, 0x36, 0xca, 0x2a, 0x9a, 0x74, 0xd6,
	0xe8, 0x75, 0xfe, 0x19, 0x01, 0x7d, 0xf0, 0x78, 0x25, 0xac, 0x69, 0xeb, 0xc7, 0xa1, 0xeb, 0x2a,
	0xb3, 0xa3, 0x17, 0x90, 0x35, 0x62, 0xdb, 0xd6, 0xe2, 0xb5, 0x2d, 0x59, 0x74, 0x19, 0x2d, 0x32,
	0x3e, 0x09, 0x60, 0x59, 0xd2, 0x73, 0x20, 0x76, 0xa7, 0xd1, 0x3a, 0x42, 0x2b, 0xf5, 0xd2, 0x19,
	0x0c, 0x48, 0x2f, 0x6a, 0xf5, 0xde, 0xf4, 0x2c, 0x76, 0x46, 0xcc, 0xbf, 0x25, 0x9d, 0x41, 0xb2,
	0xad, 0xe4, 0x20, 0xd8, 0xb1, 0xe3, 0x09, 0x0f, 0xc2, 0xd3, 0x41, 0x6b, 0x61, 0x58, 0x12, 0x28,
	0x0a, 0x4f, 0xa5, 0xfa, 0x70, 0x34, 0x0d, 0x14, 0x05, 0x9d, 0xc3, 0xa4, 0x53, 0x8d, 0x90, 0xbe,
	0x2a, 0xc1, 0xaa, 0x04, 0xf5, 0xb2, 0xcc, 0x57, 0xc0, 0xf6, 0x47, 0xe0, 0xa2, 0x1f, 0xa4, 0xa5,
	0xd7, 0x90, 0x1a, 0x8c, 0xdc, 0x14, 0xf1, 0x62, 0x7a, 0x33, 0x2f, 0x70, 0xee, 0xe2, 0x9f, 0x07,
	0x63, 0x62, 0xfe, 0x0c, 0x27, 0x3f, 0xdc, 0xa7, 0x6a, 0x73, 0xe0, 0x36, 0x4e, 0x21, 0xb6, 0xd5,
	0x06, 0x37, 0x91, 0x71, 0x1f, 0xe6, 0xf7, 0x30, 0xfb, 0xfd, 0xf3, 0xd8, 0xe4, 0xd5, 0x9f, 0x26,
	0xcf, 0xf6, 0x9b, 0xf4, 0xc9, 0x63, 0xd2, 0x1d, 0x79, 0x09, 0xc7, 0x5b, 0xa7, 0x78, 0xca, 0xdb,
	0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0b, 0x9d, 0x74, 0x07, 0xd9, 0x01, 0x00, 0x00,
}
