// Code generated by protoc-gen-go.
// source: field.proto
// DO NOT EDIT!

package mtrpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// FieldMetricSummary is the latest value received for a field metric and thresholds for the metric.
// If upper == lower == 0 then no threshold has been set on the metric.
type FieldMetricSummary struct {
	// The deviceID for the metric e.g., idu-birchfarm
	DeviceID string `protobuf:"bytes,1,opt,name=device_iD,json=deviceID" json:"device_iD,omitempty"`
	// The typeID for the metric e.g., conn
	TypeID string `protobuf:"bytes,2,opt,name=type_iD,json=typeID" json:"type_iD,omitempty"`
	// Unix time in seconds for the metric value (don't need nanos).
	Seconds int64 `protobuf:"varint,3,opt,name=seconds" json:"seconds,omitempty"`
	// The value
	Value int32 `protobuf:"varint,4,opt,name=value" json:"value,omitempty"`
	// The upper threshold for the metric to be good.
	Upper int32 `protobuf:"varint,5,opt,name=upper" json:"upper,omitempty"`
	// The lower threshold for the metric to be good.
	Lower int32 `protobuf:"varint,6,opt,name=lower" json:"lower,omitempty"`
	// the modelID for the device e.g., "Trimble NetR9"
	ModelID string `protobuf:"bytes,7,opt,name=model_iD,json=modelID" json:"model_iD,omitempty"`
}

func (m *FieldMetricSummary) Reset()                    { *m = FieldMetricSummary{} }
func (m *FieldMetricSummary) String() string            { return proto.CompactTextString(m) }
func (*FieldMetricSummary) ProtoMessage()               {}
func (*FieldMetricSummary) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

type FieldMetricSummaryResult struct {
	Result []*FieldMetricSummary `protobuf:"bytes,1,rep,name=result" json:"result,omitempty"`
}

func (m *FieldMetricSummaryResult) Reset()                    { *m = FieldMetricSummaryResult{} }
func (m *FieldMetricSummaryResult) String() string            { return proto.CompactTextString(m) }
func (*FieldMetricSummaryResult) ProtoMessage()               {}
func (*FieldMetricSummaryResult) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *FieldMetricSummaryResult) GetResult() []*FieldMetricSummary {
	if m != nil {
		return m.Result
	}
	return nil
}

type FieldMetricTag struct {
	// The deviceID for the metric e.g., idu-birchfarm
	DeviceID string `protobuf:"bytes,1,opt,name=device_iD,json=deviceID" json:"device_iD,omitempty"`
	// The typeID for the metric e.g., conn
	TypeID string `protobuf:"bytes,2,opt,name=type_iD,json=typeID" json:"type_iD,omitempty"`
	// The tag for the metric e.g., TAUP
	Tag string `protobuf:"bytes,3,opt,name=tag" json:"tag,omitempty"`
}

func (m *FieldMetricTag) Reset()                    { *m = FieldMetricTag{} }
func (m *FieldMetricTag) String() string            { return proto.CompactTextString(m) }
func (*FieldMetricTag) ProtoMessage()               {}
func (*FieldMetricTag) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

type FieldMetricTagResult struct {
	Result []*FieldMetricTag `protobuf:"bytes,1,rep,name=result" json:"result,omitempty"`
}

func (m *FieldMetricTagResult) Reset()                    { *m = FieldMetricTagResult{} }
func (m *FieldMetricTagResult) String() string            { return proto.CompactTextString(m) }
func (*FieldMetricTagResult) ProtoMessage()               {}
func (*FieldMetricTagResult) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *FieldMetricTagResult) GetResult() []*FieldMetricTag {
	if m != nil {
		return m.Result
	}
	return nil
}

type FieldMetricThreshold struct {
	// The deviceID for the metric e.g., idu-birchfarm
	DeviceID string `protobuf:"bytes,1,opt,name=device_iD,json=deviceID" json:"device_iD,omitempty"`
	// The typeID for the metric e.g., conn
	TypeID string `protobuf:"bytes,2,opt,name=type_iD,json=typeID" json:"type_iD,omitempty"`
	// The lower threshold for the metric to be good.
	Lower int32 `protobuf:"varint,3,opt,name=lower" json:"lower,omitempty"`
	// The upper threshold for the metric to be good.
	Upper int32 `protobuf:"varint,4,opt,name=upper" json:"upper,omitempty"`
}

func (m *FieldMetricThreshold) Reset()                    { *m = FieldMetricThreshold{} }
func (m *FieldMetricThreshold) String() string            { return proto.CompactTextString(m) }
func (*FieldMetricThreshold) ProtoMessage()               {}
func (*FieldMetricThreshold) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

type FieldMetricThresholdResult struct {
	Result []*FieldMetricThreshold `protobuf:"bytes,1,rep,name=result" json:"result,omitempty"`
}

func (m *FieldMetricThresholdResult) Reset()                    { *m = FieldMetricThresholdResult{} }
func (m *FieldMetricThresholdResult) String() string            { return proto.CompactTextString(m) }
func (*FieldMetricThresholdResult) ProtoMessage()               {}
func (*FieldMetricThresholdResult) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *FieldMetricThresholdResult) GetResult() []*FieldMetricThreshold {
	if m != nil {
		return m.Result
	}
	return nil
}

type FieldModel struct {
	// the modelID for the field threshold
	ModelID string `protobuf:"bytes,1,opt,name=model_iD,json=modelID" json:"model_iD,omitempty"`
}

func (m *FieldModel) Reset()                    { *m = FieldModel{} }
func (m *FieldModel) String() string            { return proto.CompactTextString(m) }
func (*FieldModel) ProtoMessage()               {}
func (*FieldModel) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

type FieldModelResult struct {
	Result []*FieldModel `protobuf:"bytes,1,rep,name=result" json:"result,omitempty"`
}

func (m *FieldModelResult) Reset()                    { *m = FieldModelResult{} }
func (m *FieldModelResult) String() string            { return proto.CompactTextString(m) }
func (*FieldModelResult) ProtoMessage()               {}
func (*FieldModelResult) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

func (m *FieldModelResult) GetResult() []*FieldModel {
	if m != nil {
		return m.Result
	}
	return nil
}

type FieldDevice struct {
	// The deviceID for the metric e.g., idu-birchfarm
	DeviceID string `protobuf:"bytes,1,opt,name=device_iD,json=deviceID" json:"device_iD,omitempty"`
	// The modelID for the metric e.g., Trimble NetR9
	ModelID string `protobuf:"bytes,2,opt,name=model_iD,json=modelID" json:"model_iD,omitempty"`
	// Decimal Latitude and Longitude, only uses three digits of precision after decimal
	Latitude  float32 `protobuf:"fixed32,3,opt,name=latitude" json:"latitude,omitempty"`
	Longitude float32 `protobuf:"fixed32,4,opt,name=longitude" json:"longitude,omitempty"`
}

func (m *FieldDevice) Reset()                    { *m = FieldDevice{} }
func (m *FieldDevice) String() string            { return proto.CompactTextString(m) }
func (*FieldDevice) ProtoMessage()               {}
func (*FieldDevice) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8} }

type FieldDeviceResult struct {
	Result []*FieldDevice `protobuf:"bytes,1,rep,name=result" json:"result,omitempty"`
}

func (m *FieldDeviceResult) Reset()                    { *m = FieldDeviceResult{} }
func (m *FieldDeviceResult) String() string            { return proto.CompactTextString(m) }
func (*FieldDeviceResult) ProtoMessage()               {}
func (*FieldDeviceResult) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{9} }

func (m *FieldDeviceResult) GetResult() []*FieldDevice {
	if m != nil {
		return m.Result
	}
	return nil
}

type FieldType struct {
	// The TypeID in the table field.type
	TypeID string `protobuf:"bytes,1,opt,name=type_iD,json=typeID" json:"type_iD,omitempty"`
}

func (m *FieldType) Reset()                    { *m = FieldType{} }
func (m *FieldType) String() string            { return proto.CompactTextString(m) }
func (*FieldType) ProtoMessage()               {}
func (*FieldType) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{10} }

type FieldTypeResult struct {
	Result []*FieldType `protobuf:"bytes,1,rep,name=result" json:"result,omitempty"`
}

func (m *FieldTypeResult) Reset()                    { *m = FieldTypeResult{} }
func (m *FieldTypeResult) String() string            { return proto.CompactTextString(m) }
func (*FieldTypeResult) ProtoMessage()               {}
func (*FieldTypeResult) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{11} }

func (m *FieldTypeResult) GetResult() []*FieldType {
	if m != nil {
		return m.Result
	}
	return nil
}

type FieldState struct {
	// the deviceID in field.device
	DeviceID string `protobuf:"bytes,1,opt,name=device_iD,json=deviceID" json:"device_iD,omitempty"`
	// the typeID in field.type
	TypeID string `protobuf:"bytes,2,opt,name=type_iD,json=typeID" json:"type_iD,omitempty"`
	// Unix time in seconds for the state in field.state (don't need nanos).
	Seconds int64 `protobuf:"varint,3,opt,name=seconds" json:"seconds,omitempty"`
	// the on/off value state in field.state
	Value bool `protobuf:"varint,4,opt,name=value" json:"value,omitempty"`
}

func (m *FieldState) Reset()                    { *m = FieldState{} }
func (m *FieldState) String() string            { return proto.CompactTextString(m) }
func (*FieldState) ProtoMessage()               {}
func (*FieldState) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{12} }

type FieldStateResult struct {
	Result []*FieldState `protobuf:"bytes,1,rep,name=result" json:"result,omitempty"`
}

func (m *FieldStateResult) Reset()                    { *m = FieldStateResult{} }
func (m *FieldStateResult) String() string            { return proto.CompactTextString(m) }
func (*FieldStateResult) ProtoMessage()               {}
func (*FieldStateResult) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{13} }

func (m *FieldStateResult) GetResult() []*FieldState {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*FieldMetricSummary)(nil), "mtrpb.FieldMetricSummary")
	proto.RegisterType((*FieldMetricSummaryResult)(nil), "mtrpb.FieldMetricSummaryResult")
	proto.RegisterType((*FieldMetricTag)(nil), "mtrpb.FieldMetricTag")
	proto.RegisterType((*FieldMetricTagResult)(nil), "mtrpb.FieldMetricTagResult")
	proto.RegisterType((*FieldMetricThreshold)(nil), "mtrpb.FieldMetricThreshold")
	proto.RegisterType((*FieldMetricThresholdResult)(nil), "mtrpb.FieldMetricThresholdResult")
	proto.RegisterType((*FieldModel)(nil), "mtrpb.FieldModel")
	proto.RegisterType((*FieldModelResult)(nil), "mtrpb.FieldModelResult")
	proto.RegisterType((*FieldDevice)(nil), "mtrpb.FieldDevice")
	proto.RegisterType((*FieldDeviceResult)(nil), "mtrpb.FieldDeviceResult")
	proto.RegisterType((*FieldType)(nil), "mtrpb.FieldType")
	proto.RegisterType((*FieldTypeResult)(nil), "mtrpb.FieldTypeResult")
	proto.RegisterType((*FieldState)(nil), "mtrpb.FieldState")
	proto.RegisterType((*FieldStateResult)(nil), "mtrpb.FieldStateResult")
}

var fileDescriptor2 = []byte{
	// 455 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x54, 0xcf, 0x8b, 0xd3, 0x40,
	0x14, 0x26, 0x4d, 0xf3, 0xeb, 0x15, 0xb4, 0x3b, 0xac, 0x98, 0xdd, 0xf5, 0x20, 0x41, 0xb0, 0x0a,
	0x16, 0x74, 0x8f, 0x22, 0x82, 0x44, 0x61, 0x0f, 0x7b, 0x30, 0xed, 0x41, 0xbc, 0x48, 0xda, 0x8c,
	0x6d, 0x60, 0xd2, 0x84, 0x74, 0x52, 0xed, 0xc9, 0xbf, 0xcd, 0xff, 0xcc, 0xcc, 0x9b, 0x49, 0x3a,
	0x49, 0x8b, 0x48, 0xc1, 0x5b, 0xde, 0xf7, 0xbe, 0xcc, 0xf7, 0xbe, 0xf7, 0xc1, 0x83, 0xd1, 0xf7,
	0x94, 0xb2, 0x64, 0x5a, 0x94, 0x39, 0xcf, 0x89, 0x95, 0xf1, 0xb2, 0x58, 0x04, 0xbf, 0x0d, 0x20,
	0x9f, 0x04, 0x7c, 0x4f, 0x79, 0x99, 0x2e, 0x67, 0x55, 0x96, 0xc5, 0xe5, 0x9e, 0xdc, 0x80, 0x97,
	0xd0, 0x5d, 0xba, 0xa4, 0xdf, 0xd2, 0xd0, 0x37, 0x9e, 0x1a, 0x13, 0x2f, 0x72, 0x25, 0x70, 0x17,
	0x92, 0xc7, 0xe0, 0xf0, 0x7d, 0x81, 0xad, 0x01, 0xb6, 0x6c, 0x51, 0xd6, 0x0d, 0x1f, 0x9c, 0x2d,
	0x5d, 0xe6, 0x9b, 0x64, 0xeb, 0x9b, 0x75, 0xc3, 0x8c, 0x9a, 0x92, 0x5c, 0x82, 0xb5, 0x8b, 0x59,
	0x45, 0xfd, 0x61, 0x8d, 0x5b, 0x91, 0x2c, 0x04, 0x5a, 0x15, 0x05, 0x2d, 0x7d, 0x4b, 0xa2, 0x58,
	0x08, 0x94, 0xe5, 0x3f, 0x6a, 0xd4, 0x96, 0x28, 0x16, 0xe4, 0x0a, 0xdc, 0x2c, 0x4f, 0x28, 0x13,
	0xaa, 0x0e, 0xaa, 0x3a, 0x58, 0xdf, 0x85, 0xc1, 0x3d, 0xf8, 0xc7, 0x16, 0x22, 0xba, 0xad, 0x18,
	0x27, 0xaf, 0xc1, 0x2e, 0xf1, 0xab, 0x76, 0x61, 0x4e, 0x46, 0x6f, 0xae, 0xa6, 0xe8, 0x7b, 0x7a,
	0xe2, 0x07, 0x45, 0x0c, 0xbe, 0xc0, 0x03, 0xad, 0x3b, 0x8f, 0x57, 0x67, 0x6e, 0x63, 0x0c, 0x26,
	0x8f, 0x57, 0xb8, 0x09, 0x2f, 0x12, 0x9f, 0xc1, 0x47, 0xb8, 0xec, 0xbe, 0xac, 0x86, 0x7c, 0xd5,
	0x1b, 0xf2, 0xd1, 0xf1, 0x90, 0x82, 0xdc, 0x0c, 0xf8, 0xb3, 0xfb, 0xcc, 0xba, 0x86, 0xd7, 0x39,
	0x4b, 0xce, 0x1c, 0xb3, 0x5d, 0xb7, 0xa9, 0xaf, 0xbb, 0x8d, 0x66, 0xa8, 0x45, 0x13, 0x7c, 0x86,
	0xeb, 0x53, 0xca, 0xca, 0xc6, 0x6d, 0xcf, 0xc6, 0xcd, 0x09, 0x1b, 0xed, 0x2f, 0x8d, 0x99, 0xe7,
	0x00, 0xb2, 0x2f, 0xc2, 0xec, 0xa4, 0x6c, 0x74, 0x53, 0x7e, 0x07, 0xe3, 0x03, 0x51, 0x29, 0xbe,
	0xe8, 0x29, 0x5e, 0x74, 0x14, 0x91, 0xd8, 0xe8, 0xfc, 0x82, 0x11, 0xa2, 0x21, 0x2e, 0xe4, 0xef,
	0xbb, 0xd2, 0xa7, 0x18, 0x74, 0xa6, 0x20, 0xd7, 0xe0, 0xb2, 0x98, 0xa7, 0xbc, 0x4a, 0x28, 0x2e,
	0x6c, 0x10, 0xb5, 0x35, 0x79, 0x02, 0x1e, 0xcb, 0x37, 0x2b, 0xd9, 0x1c, 0x62, 0xf3, 0x00, 0x04,
	0xef, 0xe1, 0x42, 0x1b, 0x40, 0x19, 0x78, 0xd9, 0x33, 0x40, 0x74, 0x03, 0x8a, 0xd9, 0x38, 0x78,
	0x06, 0x1e, 0xc2, 0xf3, 0x3a, 0x37, 0x3d, 0x4e, 0x43, 0x8f, 0x33, 0x78, 0x0b, 0x0f, 0x5b, 0x96,
	0x12, 0x99, 0xf4, 0x44, 0xc6, 0xba, 0x08, 0xf2, 0x1a, 0x89, 0x52, 0x85, 0x31, 0xe3, 0x31, 0xa7,
	0xff, 0xf7, 0x08, 0xb8, 0xea, 0x08, 0xb4, 0xb9, 0xa2, 0xe6, 0xbf, 0xe4, 0x2a, 0x89, 0x8a, 0xf0,
	0xc1, 0xf9, 0x2a, 0x2f, 0xd9, 0xc2, 0xc6, 0xbb, 0x76, 0xfb, 0x27, 0x00, 0x00, 0xff, 0xff, 0x77,
	0x0d, 0xf1, 0xf3, 0xe6, 0x04, 0x00, 0x00,
}
