DROP ROLE if exists mtradmin;
DROP ROLE if exists mtr_w;
DROP ROLE if exists mtr_r;
CREATE ROLE mtradmin WITH CREATEDB CREATEROLE LOGIN PASSWORD 'test';
CREATE ROLE mtr_w WITH LOGIN PASSWORD 'test';
CREATE ROLE mtr_r WITH LOGIN PASSWORD 'test';
